# Generated by Django 2.2.1 on 2019-05-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Muscle',
            new_name='News',
        ),
    ]
